// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"feedback/config"
	"feedback/controller"
	"feedback/middleware"
	"feedback/pkg/feishu"
	"feedback/pkg/ijwt"
	"feedback/pkg/logger"
	"feedback/repository/dao"
	"feedback/service"
	"feedback/web"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	middlewareConfig := config.NewMiddlewareConfig()
	corsMiddleware := middleware.NewCorsMiddleware(middlewareConfig)
	jwtConfig := config.NewJWTConfig()
	jwt := ijwt.NewJWT(jwtConfig)
	authMiddleware := middleware.NewAuthMiddleware(jwt)
	clientConfig := config.NewClientConfig()
	client := feishu.NewClient(clientConfig)
	zapLogger := logger.NewZapLogger()
	authService := service.NewOauth(clientConfig)
	redisConfig := config.NewRedisConfig()
	redisClient, err := dao.NewRedisClient(redisConfig)
	if err != nil {
		return nil, err
	}
	like := dao.NewLike(redisClient)
	sheetService := service.NewSheetService(like)
	appTable := config.NewAppTable()
	batchNoticeConfig := config.NewBatchNoticeConfig()
	sheet := controller.NewSheet(client, zapLogger, authService, sheetService, appTable, batchNoticeConfig)
	oauth := controller.NewOauth(clientConfig, jwt, authService, appTable)
	likeService := service.NewLikeService(like, client, zapLogger, authService)
	controllerLike := controller.NewLike(likeService, appTable, zapLogger)
	engine := web.NewGinEngine(corsMiddleware, authMiddleware, sheet, oauth, controllerLike)
	app := &App{
		r: engine,
	}
	return app, nil
}
