// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/muxi-Infra/FeedBack-Backend/config"
	"github.com/muxi-Infra/FeedBack-Backend/controller"
	"github.com/muxi-Infra/FeedBack-Backend/ioc"
	"github.com/muxi-Infra/FeedBack-Backend/llm"
	"github.com/muxi-Infra/FeedBack-Backend/middleware"
	"github.com/muxi-Infra/FeedBack-Backend/pkg/ijwt"
	"github.com/muxi-Infra/FeedBack-Backend/pkg/lark"
	"github.com/muxi-Infra/FeedBack-Backend/pkg/logger"
	"github.com/muxi-Infra/FeedBack-Backend/repository/cache"
	"github.com/muxi-Infra/FeedBack-Backend/repository/dao"
	"github.com/muxi-Infra/FeedBack-Backend/repository/es"
	"github.com/muxi-Infra/FeedBack-Backend/service"
	"github.com/muxi-Infra/FeedBack-Backend/web"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	middlewareConfig := config.NewMiddlewareConfig()
	corsMiddleware := middleware.NewCorsMiddleware(middlewareConfig)
	jwtConfig := config.NewJWTConfig()
	jwt := ijwt.NewJWT(jwtConfig)
	authMiddleware := middleware.NewAuthMiddleware(jwt)
	v := config.NewBasicAuthConfig()
	basicAuthMiddleware := middleware.NewBasicAuthMiddleware(v)
	logConfig := config.NewLogConfig()
	zapLogger := ioc.InitLogger(logConfig)
	loggerLogger := logger.NewZapLogger(zapLogger)
	loggerMiddleware := middleware.NewLoggerMiddleware(loggerLogger)
	registry := ioc.InitPrometheus()
	prometheusMiddleware := middleware.NewPrometheusMiddleware(registry)
	limiterConfig := config.NewLimiterConfig()
	redisConfig := config.NewRedisConfig()
	client := ioc.InitRedis(redisConfig)
	limitMiddleware := middleware.NewLimitMiddleware(limiterConfig, client)
	swagHandler := controller.NewSwag()
	clientConfig := config.NewClientConfig()
	larkClient := ioc.InitClient(clientConfig)
	client2 := lark.NewClient(larkClient)
	mysqlConfig := config.NewMysqlConfig()
	db := ioc.InitMysql(mysqlConfig)
	faqResolutionDAO := dao.NewFAQResolutionDAO(db)
	sheetDAO := dao.NewSheetDAO(db)
	faqdao := dao.NewFAQDAO(db)
	faqResolutionStateCache := cache.NewFAQResolutionStateCache(client)
	sheetService := service.NewSheetService(client2, loggerLogger, faqResolutionDAO, sheetDAO, faqdao, faqResolutionStateCache)
	larkMessage := config.NewLarkMessageConfig()
	ccnuBoxMessage := config.NewCCNUBoxMessageConfig()
	messageService := service.NewMessageService(client2, loggerLogger, larkMessage, ccnuBoxMessage, sheetDAO)
	sheetV1Handler := controller.NewSheet(sheetService, messageService)
	baseTable := config.NewBaseTable()
	authService := service.NewAuthService(baseTable, clientConfig, client2, loggerLogger)
	authHandler := controller.NewAuth(jwt, authService)
	aiConfig := config.NewLLMConfig()
	toolCallingChatModel, err := ioc.InitChatModel(aiConfig)
	if err != nil {
		return nil, err
	}
	embedder, err := ioc.InitLocalEmbedder(aiConfig)
	if err != nil {
		return nil, err
	}
	esConfig := config.NewESConfig()
	elasticsearchClient, err := ioc.InitESClient(esConfig)
	if err != nil {
		return nil, err
	}
	faqesRepo, err := es.NewFAQESRepo(elasticsearchClient)
	if err != nil {
		return nil, err
	}
	agent := llm.NewCustomerServiceReact(toolCallingChatModel, embedder, faqesRepo)
	aiService := service.NewChatService(agent, loggerLogger)
	aiHandler := controller.NewChat(aiService)
	messageHandler := controller.NewMessage(messageService)
	sheetV2Handler := controller.NewSheetV2(sheetService, messageService)
	engine := web.NewGinEngine(corsMiddleware, authMiddleware, basicAuthMiddleware, loggerMiddleware, prometheusMiddleware, limitMiddleware, swagHandler, sheetV1Handler, authHandler, aiHandler, messageHandler, sheetV2Handler)
	app := &App{
		r: engine,
	}
	return app, nil
}
