// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/muxi-Infra/FeedBack-Backend/config"
	"github.com/muxi-Infra/FeedBack-Backend/controller"
	"github.com/muxi-Infra/FeedBack-Backend/ioc"
	"github.com/muxi-Infra/FeedBack-Backend/middleware"
	"github.com/muxi-Infra/FeedBack-Backend/pkg/ijwt"
	"github.com/muxi-Infra/FeedBack-Backend/pkg/lark"
	"github.com/muxi-Infra/FeedBack-Backend/pkg/logger"
	"github.com/muxi-Infra/FeedBack-Backend/repository/cache"
	"github.com/muxi-Infra/FeedBack-Backend/repository/dao"
	"github.com/muxi-Infra/FeedBack-Backend/service"
	"github.com/muxi-Infra/FeedBack-Backend/web"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	middlewareConfig := config.NewMiddlewareConfig()
	corsMiddleware := middleware.NewCorsMiddleware(middlewareConfig)
	jwtConfig := config.NewJWTConfig()
	jwt := ijwt.NewJWT(jwtConfig)
	authMiddleware := middleware.NewAuthMiddleware(jwt)
	v := config.NewBasicAuthConfig()
	basicAuthMiddleware := middleware.NewBasicAuthMiddleware(v)
	logConfig := config.NewLogConfig()
	zapLogger := ioc.InitLogger(logConfig)
	loggerLogger := logger.NewZapLogger(zapLogger)
	loggerMiddleware := middleware.NewLoggerMiddleware(loggerLogger)
	registry := ioc.InitPrometheus()
	prometheusMiddleware := middleware.NewPrometheusMiddleware(registry)
	limiterConfig := config.NewLimiterConfig()
	redisConfig := config.NewRedisConfig()
	client := ioc.InitRedis(redisConfig)
	limitMiddleware := middleware.NewLimitMiddleware(limiterConfig, client)
	swag := controller.NewSwag()
	clientConfig := config.NewClientConfig()
	larkClient := ioc.InitClient(clientConfig)
	client2 := lark.NewClient(larkClient)
	mysqlConfig := config.NewMysqlConfig()
	db := ioc.InitMysql(mysqlConfig)
	faqResolutionDAO := dao.NewFAQResolutionDAO(db)
	faqResolutionStateCache := cache.NewFAQResolutionStateCache(client)
	batchNoticeConfig := config.NewBatchNoticeConfig()
	messageCountCache := cache.NewMessageCache(client)
	baseTable := config.NewBaseTable()
	authServiceImpl := service.NewAuthServiceImpl(baseTable, clientConfig, client2, loggerLogger)
	sheetService := service.NewSheetService(client2, loggerLogger, faqResolutionDAO, faqResolutionStateCache, batchNoticeConfig, messageCountCache, authServiceImpl)
	sheet := controller.NewSheet(sheetService)
	auth := controller.NewAuth(jwt, authServiceImpl)
	engine := web.NewGinEngine(corsMiddleware, authMiddleware, basicAuthMiddleware, loggerMiddleware, prometheusMiddleware, limitMiddleware, swag, sheet, auth)
	app := &App{
		r: engine,
	}
	return app, nil
}
