// Code generated by MockGen. DO NOT EDIT.
// Source: service/auth.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/muxi-Infra/FeedBack-Backend/domain"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// ExchangeIntegrationToken mocks base method.
func (m *MockAuthService) ExchangeIntegrationToken(ctx context.Context, input domain.ExchangeIntegrationTokenInput) (string, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeIntegrationToken", ctx, input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ExchangeIntegrationToken indicates an expected call of ExchangeIntegrationToken.
func (mr *MockAuthServiceMockRecorder) ExchangeIntegrationToken(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeIntegrationToken", reflect.TypeOf((*MockAuthService)(nil).ExchangeIntegrationToken), ctx, input)
}

// GetTableConfig mocks base method.
func (m *MockAuthService) GetTableConfig(projectID, tableIdentity string) (domain.TableConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableConfig", projectID, tableIdentity)
	ret0, _ := ret[0].(domain.TableConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTableConfig indicates an expected call of GetTableConfig.
func (mr *MockAuthServiceMockRecorder) GetTableConfig(projectID, tableIdentity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableConfig", reflect.TypeOf((*MockAuthService)(nil).GetTableConfig), projectID, tableIdentity)
}

// GetTenantToken mocks base method.
func (m *MockAuthService) GetTenantToken() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantToken")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetTenantToken indicates an expected call of GetTenantToken.
func (mr *MockAuthServiceMockRecorder) GetTenantToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantToken", reflect.TypeOf((*MockAuthService)(nil).GetTenantToken))
}

// RefreshTableConfig mocks base method.
func (m *MockAuthService) RefreshTableConfig() ([]domain.TableConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshTableConfig")
	ret0, _ := ret[0].([]domain.TableConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshTableConfig indicates an expected call of RefreshTableConfig.
func (mr *MockAuthServiceMockRecorder) RefreshTableConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshTableConfig", reflect.TypeOf((*MockAuthService)(nil).RefreshTableConfig))
}
