// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/muxi-Infra/FeedBack-Backend/service (interfaces: MessageService)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMessageService is a mock of MessageService interface.
type MockMessageService struct {
	ctrl     *gomock.Controller
	recorder *MockMessageServiceMockRecorder
}

// MockMessageServiceMockRecorder is the mock recorder for MockMessageService.
type MockMessageServiceMockRecorder struct {
	mock *MockMessageService
}

// NewMockMessageService creates a new mock instance.
func NewMockMessageService(ctrl *gomock.Controller) *MockMessageService {
	mock := &MockMessageService{ctrl: ctrl}
	mock.recorder = &MockMessageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageService) EXPECT() *MockMessageServiceMockRecorder {
	return m.recorder
}

// SendFeedbackNotification mocks base method.
func (m *MockMessageService) SendFeedbackNotification(arg0, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendFeedbackNotification", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendFeedbackNotification indicates an expected call of SendFeedbackNotification.
func (mr *MockMessageServiceMockRecorder) SendFeedbackNotification(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendFeedbackNotification", reflect.TypeOf((*MockMessageService)(nil).SendFeedbackNotification), arg0, arg1, arg2)
}
