// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/muxi-Infra/FeedBack-Backend/service (interfaces: MessageService)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/muxi-Infra/FeedBack-Backend/domain"
)

// MockMessageService is a mock of MessageService interface.
type MockMessageService struct {
	ctrl     *gomock.Controller
	recorder *MockMessageServiceMockRecorder
}

// MockMessageServiceMockRecorder is the mock recorder for MockMessageService.
type MockMessageServiceMockRecorder struct {
	mock *MockMessageService
}

// NewMockMessageService creates a new mock instance.
func NewMockMessageService(ctrl *gomock.Controller) *MockMessageService {
	mock := &MockMessageService{ctrl: ctrl}
	mock.recorder = &MockMessageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageService) EXPECT() *MockMessageServiceMockRecorder {
	return m.recorder
}

// GetCCNUBoxPendingNotifications mocks base method.
func (m *MockMessageService) GetCCNUBoxPendingNotifications(arg0 *domain.TableConfig) ([]domain.NotificationRecipient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCCNUBoxPendingNotifications", arg0)
	ret0, _ := ret[0].([]domain.NotificationRecipient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCCNUBoxPendingNotifications indicates an expected call of GetCCNUBoxPendingNotifications.
func (mr *MockMessageServiceMockRecorder) GetCCNUBoxPendingNotifications(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCCNUBoxPendingNotifications", reflect.TypeOf((*MockMessageService)(nil).GetCCNUBoxPendingNotifications), arg0)
}

// SendCCNUBoxNotification mocks base method.
func (m *MockMessageService) SendCCNUBoxNotification(arg0 *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCCNUBoxNotification", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendCCNUBoxNotification indicates an expected call of SendCCNUBoxNotification.
func (mr *MockMessageServiceMockRecorder) SendCCNUBoxNotification(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCCNUBoxNotification", reflect.TypeOf((*MockMessageService)(nil).SendCCNUBoxNotification), arg0)
}

// SendLarkNotification mocks base method.
func (m *MockMessageService) SendLarkNotification(arg0, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendLarkNotification", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendLarkNotification indicates an expected call of SendLarkNotification.
func (mr *MockMessageServiceMockRecorder) SendLarkNotification(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLarkNotification", reflect.TypeOf((*MockMessageService)(nil).SendLarkNotification), arg0, arg1, arg2)
}

// TriggerNotification mocks base method.
func (m *MockMessageService) TriggerNotification(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerNotification", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// TriggerNotification indicates an expected call of TriggerNotification.
func (mr *MockMessageServiceMockRecorder) TriggerNotification(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerNotification", reflect.TypeOf((*MockMessageService)(nil).TriggerNotification), arg0)
}
