// Code generated by MockGen. DO NOT EDIT.
// Source: ../oauth.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	service "github.com/muxi-Infra/FeedBack-Backend/service"
	oauth2 "golang.org/x/oauth2"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// Code2Token mocks base method.
func (m *MockAuthService) Code2Token(ctx context.Context, code, codeVerifier string) (*oauth2.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Code2Token", ctx, code, codeVerifier)
	ret0, _ := ret[0].(*oauth2.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Code2Token indicates an expected call of Code2Token.
func (mr *MockAuthServiceMockRecorder) Code2Token(ctx, code, codeVerifier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Code2Token", reflect.TypeOf((*MockAuthService)(nil).Code2Token), ctx, code, codeVerifier)
}

// GetLoginURL mocks base method.
func (m *MockAuthService) GetLoginURL(state, verifier string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoginURL", state, verifier)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetLoginURL indicates an expected call of GetLoginURL.
func (mr *MockAuthServiceMockRecorder) GetLoginURL(state, verifier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoginURL", reflect.TypeOf((*MockAuthService)(nil).GetLoginURL), state, verifier)
}

// GetUserInfoByToken mocks base method.
func (m *MockAuthService) GetUserInfoByToken(ctx context.Context, token *oauth2.Token) (*service.UserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfoByToken", ctx, token)
	ret0, _ := ret[0].(*service.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfoByToken indicates an expected call of GetUserInfoByToken.
func (mr *MockAuthServiceMockRecorder) GetUserInfoByToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfoByToken", reflect.TypeOf((*MockAuthService)(nil).GetUserInfoByToken), ctx, token)
}

// StartRefresh mocks base method.
func (m *MockAuthService) StartRefresh(accessToken, refreshToken string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartRefresh", accessToken, refreshToken)
}

// StartRefresh indicates an expected call of StartRefresh.
func (mr *MockAuthServiceMockRecorder) StartRefresh(accessToken, refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartRefresh", reflect.TypeOf((*MockAuthService)(nil).StartRefresh), accessToken, refreshToken)
}

// MockAuthTokenProvider is a mock of AuthTokenProvider interface.
type MockAuthTokenProvider struct {
	ctrl     *gomock.Controller
	recorder *MockAuthTokenProviderMockRecorder
}

// MockAuthTokenProviderMockRecorder is the mock recorder for MockAuthTokenProvider.
type MockAuthTokenProviderMockRecorder struct {
	mock *MockAuthTokenProvider
}

// NewMockAuthTokenProvider creates a new mock instance.
func NewMockAuthTokenProvider(ctrl *gomock.Controller) *MockAuthTokenProvider {
	mock := &MockAuthTokenProvider{ctrl: ctrl}
	mock.recorder = &MockAuthTokenProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthTokenProvider) EXPECT() *MockAuthTokenProviderMockRecorder {
	return m.recorder
}

// GetAccessToken mocks base method.
func (m *MockAuthTokenProvider) GetAccessToken() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessToken")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAccessToken indicates an expected call of GetAccessToken.
func (mr *MockAuthTokenProviderMockRecorder) GetAccessToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessToken", reflect.TypeOf((*MockAuthTokenProvider)(nil).GetAccessToken))
}

// GetTenantAccessToken mocks base method.
func (m *MockAuthTokenProvider) GetTenantAccessToken() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantAccessToken")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetTenantAccessToken indicates an expected call of GetTenantAccessToken.
func (mr *MockAuthTokenProviderMockRecorder) GetTenantAccessToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantAccessToken", reflect.TypeOf((*MockAuthTokenProvider)(nil).GetTenantAccessToken))
}
