// Code generated by MockGen. DO NOT EDIT.
// Source: ../sheet.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	larkdrive "github.com/larksuite/oapi-sdk-go/v3/service/drive/v1"
	DTO "github.com/muxi-Infra/FeedBack-Backend/domain/DTO"
)

// MockSheetService is a mock of SheetService interface.
type MockSheetService struct {
	ctrl     *gomock.Controller
	recorder *MockSheetServiceMockRecorder
}

// MockSheetServiceMockRecorder is the mock recorder for MockSheetService.
type MockSheetServiceMockRecorder struct {
	mock *MockSheetService
}

// NewMockSheetService creates a new mock instance.
func NewMockSheetService(ctrl *gomock.Controller) *MockSheetService {
	mock := &MockSheetService{ctrl: ctrl}
	mock.recorder = &MockSheetServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSheetService) EXPECT() *MockSheetServiceMockRecorder {
	return m.recorder
}

// CreateRecord mocks base method.
func (m *MockSheetService) CreateRecord(record DTO.TableRecord, tableConfig DTO.TableConfig) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRecord", record, tableConfig)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRecord indicates an expected call of CreateRecord.
func (mr *MockSheetServiceMockRecorder) CreateRecord(record, tableConfig interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRecord", reflect.TypeOf((*MockSheetService)(nil).CreateRecord), record, tableConfig)
}

// GetNormalProblemTableRecord mocks base method.
func (m *MockSheetService) GetNormalProblemTableRecord(fieldNames []string, tableConfig DTO.TableConfig) (*DTO.TableRecords, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNormalProblemTableRecord", fieldNames, tableConfig)
	ret0, _ := ret[0].(*DTO.TableRecords)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNormalProblemTableRecord indicates an expected call of GetNormalProblemTableRecord.
func (mr *MockSheetServiceMockRecorder) GetNormalProblemTableRecord(fieldNames, tableConfig interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNormalProblemTableRecord", reflect.TypeOf((*MockSheetService)(nil).GetNormalProblemTableRecord), fieldNames, tableConfig)
}

// GetPhotoUrl mocks base method.
func (m *MockSheetService) GetPhotoUrl(fileTokens []string) (*larkdrive.BatchGetTmpDownloadUrlMediaResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhotoUrl", fileTokens)
	ret0, _ := ret[0].(*larkdrive.BatchGetTmpDownloadUrlMediaResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPhotoUrl indicates an expected call of GetPhotoUrl.
func (mr *MockSheetServiceMockRecorder) GetPhotoUrl(fileTokens interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhotoUrl", reflect.TypeOf((*MockSheetService)(nil).GetPhotoUrl), fileTokens)
}

// GetTableRecordReqByKey mocks base method.
func (m *MockSheetService) GetTableRecordReqByKey(keyField DTO.TableField, fieldNames []string, pageToken string, tableConfig DTO.TableConfig) (*DTO.TableRecords, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableRecordReqByKey", keyField, fieldNames, pageToken, tableConfig)
	ret0, _ := ret[0].(*DTO.TableRecords)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTableRecordReqByKey indicates an expected call of GetTableRecordReqByKey.
func (mr *MockSheetServiceMockRecorder) GetTableRecordReqByKey(keyField, fieldNames, pageToken, tableConfig interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableRecordReqByKey", reflect.TypeOf((*MockSheetService)(nil).GetTableRecordReqByKey), keyField, fieldNames, pageToken, tableConfig)
}

// GetUserLikeRecord mocks base method.
func (m *MockSheetService) GetUserLikeRecord(recordID, userID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserLikeRecord", recordID, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserLikeRecord indicates an expected call of GetUserLikeRecord.
func (mr *MockSheetServiceMockRecorder) GetUserLikeRecord(recordID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserLikeRecord", reflect.TypeOf((*MockSheetService)(nil).GetUserLikeRecord), recordID, userID)
}
