// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/table-config/refresh": {
            "get": {
                "description": "刷新表格 token 配置接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "刷新表格 token 配置接口",
                "responses": {
                    "200": {
                        "description": "成功返回目前支持索引的表格的公开配置",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/token": {
            "post": {
                "description": "获取 token 接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "获取 token 接口",
                "parameters": [
                    {
                        "description": "获取Token请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.GenerateTokenReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回 JWT 令牌",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/health": {
            "get": {
                "description": "健康检查，返回当前服务占用的资源等信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "健康检查，返回当前服务占用的资源等信息",
                "operationId": "health-check",
                "responses": {
                    "200": {
                        "description": "成功返回健康检查结果",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.HealthCheckResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/sheet/photos/url": {
            "get": {
                "description": "根据文件Token获取截图的临时下载URL，URL有效期为24小时",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sheet"
                ],
                "summary": "获取截图临时URL",
                "operationId": "get-photo-url",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "附件 token",
                        "name": "file_tokens",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回临时URL信息",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误或飞书接口调用失败",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/sheet/records": {
            "get": {
                "description": "根据指定条件查询多维表格中的记录数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sheet"
                ],
                "summary": "获取多维表格记录",
                "operationId": "get-table-record",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用于查询记录的关键值，一般使用学号的字段名",
                        "name": "key_field",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用于查询记录的关键值，一般使用学号的字段值",
                        "name": "key_value",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "分页参数,第一次不需要",
                        "name": "page_token",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "需要查询的字段名",
                        "name": "record_names",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "table_identify",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回查询结果",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误或飞书接口调用失败",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "向指定的多维表格应用中添加记录数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sheet"
                ],
                "summary": "创建多维表格记录",
                "operationId": "create-table-record",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "新增记录请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreatTableRecordReg"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回创建记录结果",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误或飞书接口调用失败",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/sheet/records/faq": {
            "get": {
                "description": "根据指定条件查询多维表格中的记录数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sheet"
                ],
                "summary": "获取常见问题记录",
                "operationId": "get-app-table-faq-problem-record",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "需要查询的字段名",
                        "name": "record_names",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "学号，用于标记用户身份",
                        "name": "student_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "table_identify",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回查询结果",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误或飞书接口调用失败",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "更新FAQ解决方案的 已解决/未解决 状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sheet"
                ],
                "summary": "更新FAQ解决方案的 已解决/未解决 状态",
                "operationId": "faq-resolution-update",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "查询记录请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.FAQResolutionUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回查询结果",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误或飞书接口调用失败",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "request.CreatTableRecordReg": {
            "type": "object",
            "required": [
                "records",
                "table_identify"
            ],
            "properties": {
                "records": {
                    "description": "记录列表",
                    "type": "object",
                    "additionalProperties": {}
                },
                "table_identify": {
                    "type": "string"
                }
            }
        },
        "request.FAQResolutionUpdateReq": {
            "type": "object",
            "required": [
                "is_resolved",
                "record_id",
                "table_identify",
                "user_id"
            ],
            "properties": {
                "is_resolved": {
                    "type": "boolean"
                },
                "record_id": {
                    "type": "string"
                },
                "table_identify": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "request.GenerateTokenReq": {
            "type": "object",
            "required": [
                "table_identity"
            ],
            "properties": {
                "table_identity": {
                    "description": "反馈表格 Identity，反馈表的唯一标识",
                    "type": "string"
                }
            }
        },
        "response.HealthCheckResponse": {
            "type": "object",
            "properties": {
                "process": {
                    "description": "Process 当前进程的运行状态",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.ProcessStats"
                        }
                    ]
                },
                "response_ms": {
                    "description": "ResponseMs 响应耗时，单位毫秒",
                    "type": "string"
                },
                "status": {
                    "description": "Status 服务状态，例如 \"ok\"",
                    "type": "string"
                },
                "system": {
                    "description": "System 系统资源使用情况",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.SystemStats"
                        }
                    ]
                }
            }
        },
        "response.ProcessStats": {
            "type": "object",
            "properties": {
                "cpu_percent": {
                    "description": "CPUPercent 进程 CPU 使用率（%）",
                    "type": "string"
                },
                "go_heap_alloc_mb": {
                    "description": "GoHeapAllocMB Go 堆分配的内存（MB）",
                    "type": "string"
                },
                "goroutines": {
                    "description": "Goroutines 当前运行的 goroutine 数",
                    "type": "string"
                },
                "memory_rss_mb": {
                    "description": "MemoryRSSMB 进程常驻内存（MB）",
                    "type": "string"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "response.SystemStats": {
            "type": "object",
            "properties": {
                "cpu_percent": {
                    "description": "CPUPercent CPU 使用率（%）",
                    "type": "string"
                },
                "disk_percent": {
                    "description": "DiskPercent 磁盘使用率（%）",
                    "type": "string"
                },
                "disk_total": {
                    "description": "DiskTotalGB 磁盘总量（GB）",
                    "type": "string"
                },
                "disk_used": {
                    "description": "DiskUsedGB 已使用磁盘（GB）",
                    "type": "string"
                },
                "memory_percent": {
                    "description": "MemoryPercent 内存使用率（%）",
                    "type": "string"
                },
                "memory_total": {
                    "description": "MemoryTotalMB 内存总量（MB）",
                    "type": "string"
                },
                "memory_used": {
                    "description": "MemoryUsedMB 已使用内存（MB）",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "木犀反馈系统 API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
