// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "显示欢迎页面并提供飞书登录入口",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "首页",
                "responses": {
                    "200": {
                        "description": "HTML 页面",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/callback": {
            "get": {
                "description": "处理飞书 OAuth2 回调并获取用户信息",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "授权回调",
                "parameters": [
                    {
                        "type": "string",
                        "description": "OAuth 状态",
                        "name": "state",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "授权码",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "HTML 页面",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "302": {
                        "description": "重定向回首页",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/generate_token": {
            "post": {
                "description": "封装 token 接口，将飞书 token 简单封装成 JWT 令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "封装 token 接口",
                "parameters": [
                    {
                        "description": "封装 token 请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.GenerateTokenReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回 JWT 令牌",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/login": {
            "get": {
                "description": "重定向到飞书 OAuth2 授权页面",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "跳转飞书授权",
                "responses": {
                    "302": {
                        "description": "重定向到飞书登录",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/refresh_token": {
            "post": {
                "description": "使用 refresh_token 刷新 access_token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "刷新Token",
                "parameters": [
                    {
                        "description": "刷新 token 请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RefreshTokenReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回新的 token 信息",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误或飞书接口调用失败",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/sheet/copyapp": {
            "post": {
                "description": "基于已有的模板 AppToken 复制创建一个新的多维表格应用",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sheet"
                ],
                "summary": "从模版复制创建多维表格",
                "operationId": "copy-app",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "复制表格请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CopyAppReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回复制结果",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误或飞书接口调用失败",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/sheet/createapp": {
            "post": {
                "description": "基于给定的名称和文件夹 Token 创建一个新的多维表格应用",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sheet"
                ],
                "summary": "创建多维表格",
                "operationId": "create-app",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "创建表格请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreateAppReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回创建结果",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误或飞书接口调用失败",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/sheet/createrecord": {
            "post": {
                "description": "向指定的多维表格应用中添加记录数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sheet"
                ],
                "summary": "创建多维表格记录",
                "operationId": "create-app-table-record",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "新增记录请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreateAppTableRecordReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回创建记录结果",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误或飞书接口调用失败",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "request.CopyAppReq": {
            "type": "object",
            "required": [
                "app_token",
                "name",
                "time_zone",
                "without_content"
            ],
            "properties": {
                "app_token": {
                    "description": "需要复制的表格的token",
                    "type": "string"
                },
                "folder_token": {
                    "description": "可以为空，但是要有",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "time_zone": {
                    "description": "时区,例如: Asia/Shanghai",
                    "type": "string"
                },
                "without_content": {
                    "description": "是否复制内容",
                    "type": "boolean"
                }
            }
        },
        "request.CreateAppReq": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "folder_token": {
                    "description": "可以为空，但是要有",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "request.CreateAppTableRecordReq": {
            "type": "object",
            "required": [
                "app_token",
                "fields",
                "table_id"
            ],
            "properties": {
                "app_token": {
                    "type": "string"
                },
                "fields": {
                    "description": "记录的字段",
                    "type": "object",
                    "additionalProperties": true
                },
                "ignore_consistency_check": {
                    "description": "UserIdType             string                 ` + "`" + `json:\"user_id_type,omitempty\"` + "`" + `\nClientToken            string                 ` + "`" + `json:\"client_token,omitempty\"` + "`" + `",
                    "type": "boolean"
                },
                "table_id": {
                    "type": "string"
                }
            }
        },
        "request.GenerateTokenReq": {
            "type": "object",
            "required": [
                "token"
            ],
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "request.RefreshTokenReq": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
