// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/table-config/refresh": {
            "get": {
                "description": "刷新并重新加载系统中所有支持的表格配置信息，返回当前可用的表格列表及其基本信息。通常用于配置更新后的缓存刷新。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "刷新表格配置缓存",
                "operationId": "refresh-table-config",
                "responses": {
                    "200": {
                        "description": "成功返回目前支持索引的表格的公开配置",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/table-config/token": {
            "post": {
                "description": "根据表格标识符生成JWT访问令牌，用于后续的表格数据操作。该令牌包含表格配置信息和访问权限。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "获取表格访问令牌",
                "operationId": "get-table-token",
                "parameters": [
                    {
                        "description": "获取Token请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.GenerateTableTokenReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回 JWT 令牌",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.GenerateTableTokenResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/tenant/token": {
            "post": {
                "description": "获取飞书应用的租户访问令牌，主要用于文件上传、图片处理等需要应用级权限的操作。该令牌具有较高的访问权限。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "获取租户访问令牌",
                "operationId": "get-tenant-token",
                "responses": {
                    "200": {
                        "description": "成功返回 JWT 令牌",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.GenerateTenantToken"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/health": {
            "get": {
                "description": "检查系统运行状态，返回服务健康信息、资源使用情况等监控数据。用于负载均衡器健康检查和系统监控。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "系统健康检查",
                "operationId": "health-check",
                "responses": {
                    "200": {
                        "description": "系统运行正常，返回健康检查详情",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.HealthCheckResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "系统异常或部分服务不可用",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/openapi": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "接口直接返回 docs/openapi3.yaml yaml格式的原始内容，使用BasicAuth进行验证",
                "produces": [
                    "application/x-yaml"
                ],
                "tags": [
                    "Swag"
                ],
                "summary": "获取 OpenAPI3 接口文档 (YAML)",
                "operationId": "get-openapi3",
                "responses": {
                    "200": {
                        "description": "成功返回 OpenAPI3 文档内容",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "未授权，BasicAuth 验证失败",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/sheet/photos/url": {
            "get": {
                "description": "根据文件Token列表批量获取截图的临时下载URL，用于前端展示或下载图片。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sheet"
                ],
                "summary": "获取截图临时URL",
                "operationId": "get-photo-url",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "附件 token",
                        "name": "file_tokens",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回临时URL信息",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误或飞书接口调用失败",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/sheet/records": {
            "get": {
                "description": "根据指定的字段条件查询用户的历史反馈记录，支持分页查询。通常用于查看用户之前提交的反馈内容。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sheet"
                ],
                "summary": "查询历史反馈记录",
                "operationId": "get-table-record",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用于查询记录的关键值，一般使用学号的字段名",
                        "name": "key_field",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用于查询记录的关键值，一般使用学号的字段值",
                        "name": "key_value",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "分页参数,第一次不需要",
                        "name": "page_token",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "需要查询的字段名",
                        "name": "record_names",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "table_identify",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回查询结果",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.GetTableRecordResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误或飞书接口调用失败",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "向指定的多维表格应用中添加用户反馈记录，支持文本内容、截图附件和联系方式。创建成功后会异步发送通知消息。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sheet"
                ],
                "summary": "创建反馈记录",
                "operationId": "create-table-record",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "新增记录请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreatTableRecordReg"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回创建记录结果",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.CreatTableRecordResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误或飞书接口调用失败",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/sheet/records/faq": {
            "get": {
                "description": "根据学号查询用户相关的常见问题记录及其解决状态。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sheet"
                ],
                "summary": "查询FAQ问题记录",
                "operationId": "get-faq-resolution-record",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "需要查询的字段名",
                        "name": "record_names",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "学号，用于标记用户身份",
                        "name": "student_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "table_identify",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回查询结果",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.GetFAQProblemTableRecordResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误或飞书接口调用失败",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "用户更新FAQ问题的解决状态，将问题标记为已解决或未解决。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sheet"
                ],
                "summary": "标记FAQ问题解决状态",
                "operationId": "update-faq-resolution",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "更新FAQ解决状态请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.FAQResolutionUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功更新FAQ解决状态",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误或飞书接口调用失败",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.FAQTableRecord": {
            "type": "object",
            "properties": {
                "is_resolved": {
                    "type": "string"
                },
                "record": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "record_id": {
                    "type": "string"
                }
            }
        },
        "domain.TableRecord": {
            "type": "object",
            "properties": {
                "record": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "record_id": {
                    "type": "string"
                }
            }
        },
        "request.CreatTableRecordReg": {
            "type": "object",
            "required": [
                "content",
                "student_id",
                "table_identify"
            ],
            "properties": {
                "contact_info": {
                    "description": "联系方式，可选",
                    "type": "string"
                },
                "content": {
                    "description": "反馈内容",
                    "type": "string"
                },
                "extra_record": {
                    "description": "额外记录列表，可选",
                    "type": "object",
                    "additionalProperties": {}
                },
                "images": {
                    "description": "图片附件 URL 列表，可选",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "student_id": {
                    "description": "学号，用于标记用户身份",
                    "type": "string"
                },
                "table_identify": {
                    "type": "string"
                }
            }
        },
        "request.FAQResolutionUpdateReq": {
            "type": "object",
            "required": [
                "is_resolved",
                "record_id",
                "resolved_field_name",
                "table_identify",
                "unresolved_field_name",
                "user_id"
            ],
            "properties": {
                "is_resolved": {
                    "type": "boolean"
                },
                "record_id": {
                    "type": "string"
                },
                "resolved_field_name": {
                    "type": "string"
                },
                "table_identify": {
                    "type": "string"
                },
                "unresolved_field_name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "request.GenerateTableTokenReq": {
            "type": "object",
            "required": [
                "table_identify"
            ],
            "properties": {
                "table_identify": {
                    "description": "反馈表格 Identify，反馈表的唯一标识",
                    "type": "string"
                }
            }
        },
        "response.CreatTableRecordResp": {
            "type": "object",
            "properties": {
                "record_id": {
                    "type": "string"
                }
            }
        },
        "response.GenerateTableTokenResp": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                }
            }
        },
        "response.GenerateTenantToken": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                }
            }
        },
        "response.GetFAQProblemTableRecordResp": {
            "type": "object",
            "properties": {
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.FAQTableRecord"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.GetTableRecordResp": {
            "type": "object",
            "properties": {
                "has_more": {
                    "type": "boolean"
                },
                "page_token": {
                    "type": "string"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.TableRecord"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.HealthCheckResponse": {
            "type": "object",
            "properties": {
                "process": {
                    "description": "Process 当前进程的运行状态",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.ProcessStats"
                        }
                    ]
                },
                "response_ms": {
                    "description": "ResponseMs 响应耗时，单位毫秒",
                    "type": "string"
                },
                "status": {
                    "description": "Status 服务状态，例如 \"ok\"",
                    "type": "string"
                },
                "system": {
                    "description": "System 系统资源使用情况",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.SystemStats"
                        }
                    ]
                }
            }
        },
        "response.ProcessStats": {
            "type": "object",
            "properties": {
                "cpu_percent": {
                    "description": "CPUPercent 进程 CPU 使用率（%）",
                    "type": "string"
                },
                "go_heap_alloc_mb": {
                    "description": "GoHeapAllocMB Go 堆分配的内存（MB）",
                    "type": "string"
                },
                "goroutines": {
                    "description": "Goroutines 当前运行的 goroutine 数",
                    "type": "string"
                },
                "memory_rss_mb": {
                    "description": "MemoryRSSMB 进程常驻内存（MB）",
                    "type": "string"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "response.SystemStats": {
            "type": "object",
            "properties": {
                "cpu_percent": {
                    "description": "CPUPercent CPU 使用率（%）",
                    "type": "string"
                },
                "disk_percent": {
                    "description": "DiskPercent 磁盘使用率（%）",
                    "type": "string"
                },
                "disk_total": {
                    "description": "DiskTotalGB 磁盘总量（GB）",
                    "type": "string"
                },
                "disk_used": {
                    "description": "DiskUsedGB 已使用磁盘（GB）",
                    "type": "string"
                },
                "memory_percent": {
                    "description": "MemoryPercent 内存使用率（%）",
                    "type": "string"
                },
                "memory_total": {
                    "description": "MemoryTotalMB 内存总量（MB）",
                    "type": "string"
                },
                "memory_used": {
                    "description": "MemoryUsedMB 已使用内存（MB）",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "木犀反馈系统 API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
